apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  #namespace: namespace1 # Set by cross-cutting in kustomization.yaml
destination:
  server: https://kubernetes.default.svc
  #namespace: namespace1
spec:
  syncPolicy:
    syncOptions:
      - PrunePropagationPolicy=undefined
      - CreateNamespace=true
      - Validate=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=false
      - FluxSubsystem=false
      - AutoCreateFluxResources=false
      - Replace=false
      - retry=false
      - applicationsSync=undefined
      - preserveResourcesOnDeletion=false
  sources:
    - repoURL: https://github.com/stefanprodan/podinfo.git
      path: charts/podinfo
      targetRevision: master
      helm:
        valueFiles:
          - $values/podinfo/values.yaml
    - repoURL: https://github.com/roscoejp/flux-sample-config
      targetRevision: main
      ref: values
